### PR TITLE
No transparency

### PR DESCRIPTION
**Pull request by YoungElPaso**
Throws an error if one of the colors being contrasted is transparent.

### CODE REVIEW

**Comment by johno** [comment]
This is great, thanks!

Though, in order to support one of my current uses for this module, it'd be great if we could make this addition configurable via an option:

``` js
contrast.score(colorOne, colorTwo, { ignoreTransparency: true })
```

I definitely think it is appropriate to default to throwing an error when transparent, but I'd like to be able to "turn it off". If that makes sense?

And thank you for your contribution!

**Comment by YoungElPaso** [comment]
Heh, no problem! I'm doing some automated testing of some web pages I maintain and needed a handy way to check contrast, so your module fit the bill :) Also, as for your suggestion, as soon as I pressed  the pull request button I though the exact same thing. "Wait a minute...this might break someone else's installation...better add an option..."  So yeah, I'll try to add that in asap, makes a lot sense.

**Comment by johno** [comment]
Perfection, thanks!

**Comment by johno** [comment]
Ping?

Please let me know if you plan on adding the option. If you're busy, no worries, I can merge this in and implement it as well. Thank you!

**Comment by johno** [comment]
Thanks!

**Pull request merged**
